# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20160405_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
